export const sectorOptions = [
  'Technology and Infrastructure',
  'Bank',
  'Multi Finance',
  'E-Commerce and Market Place',
  'Educational Tech',
  'Agri Tech',
  'Payment Gateway',
  'Data Center',
  'Travel Tech',
  'Food Tech',
  'Koperasi Digital',
  'Bank BPR',
  'Consultant',
  'Palm Oil Mill',
  'Electricity Supply (renewable energy & non-renewable energy)',
  'Hospital',
  'Warehousing and Storage',
  'Terminals',
  'Rail Transportation',
  'Sea and Inland Water Transportation',
  'BUMN - Energy, Oil and Gas (Manufacture of coke and refined petroleum products))',
  'BUMN - Insurance',
  'BUMN Construction',
  'Transport and Logistics',
  'Pharmacy',
  'BUMN - Transport and Logistics',
  'Pengelolaan Dana Pensiun',
  'Perdagangan Aset Digital/Kripto',
  'Healthcare',
  'Undefined',
  'Technology Provider',
  'Agriculture, Forestry and Fishing',
  'Mining and Quarrying',
  'Leather and Leather Products',
  'Food products, Beverages and Tobacco',
  'Textiles and Textile Products',
  'Pulp, paper and paper products',
  'Publishing companies',
  'Wood and wood products',
  'Printing companies',
  'Manufacture of coke and refined petroleum products',
  'Nuclear fuel',
  'Chemicals, chemical products and fibers',
  'Rubber and plastic products',
  'Non-metallic mineral products',
  'Pharmaceuticals',
  'Concrete, cement, lime, plaster etc',
  'Machinery and equipment',
  'Basic metals and fabricated metal products',
  'Electrical and optical equipment',
  'Aerospace',
  'Shipbuilding',
  'Other transport equipment',
  'Electricity supply',
  'Manufacturing not elsewhere classified',
  'Recycling',
  'Gas supply',
  'Construction',
  'Water supply',
  'Wholesale and retail trade;Repair of motor Vehicles, Motorcycles and Personal and household Goods',
  'Hotels and restaurants',
  'Transport, storage and communication',
  'Financial intermediation; real estate; renting',
  'Information technology',
  'Engineering services',
  'Other services',
  'Public administration',
  'Education',
  'Health and social work',
  'Other social services',
  'Power Generation and Electric Power Transaction',
  'General Manufacturing',
  'Chemical Production',
  'Energy Industries (Renewable/Non-renewable Sources) Project Verification',
  'Energy Demand Project Verification',
  'Energy Distribution Project Verification',
  'General',
  'Manufacturing Industries Project Validation',
  'Chemical Industry Project Validation',
  'Energy Distribution Project Validation',
  'Energy Industries (Renewable/Non-renewable Sources) Project Validation',
  'Energy Demand Project Validation',
  'Combustion Fossil Fuel (NEK)',
  'Mining/Mineral Production Project Verification',
  'Chemical Industry Project Verification',
  'Afforestation and Reforestation Project Verification',
  'Insurance',
  'Financial Technology',
  'Health Technology',
  'HRIS Tech',
  'Logistic Technology',
  'Artificial Intelligence (AI)',
  'Software as A Services (SaaS)',
  'E-Wallet',
  'Training Center',
  'Palm Oil Plantation',
  'Collecting point of Used Cooking Oil',
  'Medical Laboratory',
  'Port',
  'Operator Port',
  'Trading',
  'BUMN - Energy, Oil and Gas (Mining and Quarrying)',
  'Trading in Waste Agriculture Product',
  'BUMN - Agriculture, Forestry and Fishing',
  'BUMN - Printing',
  'BUMN - Tech Companies',
  'Lawfirm',
  'BUMN Pharmaceuticals',
  'Koperasi Simpan Pinjam',
  'Pialang Berjangka',
  'P2P Lending',
  'Perusahaan Sekuritas',
  'Freight Forwading',
  'Financial Service and Capital Market',
] as const

export type SectorOption = (typeof sectorOptions)[number]
